"""empty message

Revision ID: 10985d9f83e3
Revises: 80bacc20a0a4
Create Date: 2025-12-18 16:42:42.403595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10985d9f83e3'
down_revision = '80bacc20a0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caretaker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caretaker_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'caretaker', ['caretaker_id'], ['id'])

    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caretaker_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'caretaker', ['caretaker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('caretaker_id')

    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('caretaker_id')

    op.drop_table('caretaker')
    # ### end Alembic commands ###
