"""empty message

Revision ID: 12ac45c0653c
Revises: 10985d9f83e3
Create Date: 2025-12-19 15:40:12.503753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ac45c0653c'
down_revision = '10985d9f83e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('pet_count')

    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_column('pet_count')

    # ### end Alembic commands ###
