"""Fixes columns for Cat model

Revision ID: 98423d764436
Revises: 601e465a9331
Create Date: 2025-10-25 18:02:12.409381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98423d764436'
down_revision = '601e465a9331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('personality', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_column('personality')
        batch_op.drop_column('color')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
